[project]
name = "dual-goal-representations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "distrax>=0.1.7",
    "einops>=0.8.2",
    "flax>=0.12.3",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "jax[cuda12]>=0.9.0.1",
    "matplotlib>=3.10.8",
    "ml-collections>=1.1.0",
    "ogbench>=1.2.1",
    "optax>=0.2.7",
    "orbax>=0.1.9",
    "orbax-checkpoint>=0.11.32",
    "pypdf>=6.9.2",
    "rootutils>=1.0.7",
    "wandb[media]==0.25",
]

[dependency-groups]
dev = [
    "ruff>=0.15.9",
]
